### ISSUE TITLE
3.1.11 bugfix and small features release

### ISSUE THREAD

**Issue by Kerooker** [kotlintest/kotlintest#489]
Given that version 3.1.10 has some bugs that were already fixed in master branch, we should release a minor version to correct those bugs and add some smaller features.

This issue creates a small checklist on what can be release for 3.1.11, as some users (me included) are suffering a bit with some bugs that were already fixed. All commits related to this issue should be taken to the branch `release/3.1.11`. The last commit in release `3.1.10` was bc2da5a95fca67d9513f7a898a35ada153b63ae4.

- [x] Add infix support to map matchers #417  by @checketts 
- [x] Updated docs for Gen.int() #419
- [x] Add documentation to Date matchers #420 
- [x] Refactor Period matchers to accept any TemporalAmount #423 
- [x] Add arrow-assertion Failure matcher that checks underlying throwable equality #427 by @osheari1 
- [x] Refactor double matchers to include an infix modifier (#429)
- [x] BugFix: Double matcher shouldNotBeExactly #432
- [x] Improve empty error message in collections #438
- [x] Add unit tests for new matchers 'shouldNotBePositive', 'shouldNotBeNegative' and unit tests for both #435 by @raverona  
- [x] Add documentation for starts/end with collection matchers #446 by @IsabelleNP 
- [x] Add remaining infix support for file, floats, sequences, types, and uri #445 by @checketts 
- [x] Add infix support to string matchers by @checketts 
- [x] In the case of a single thread for a test case, use the main thread #447 
- [x] Config with invocations > 1 stuck if test fails #413 
- [x] Add shouldBeNotTrue and shouldBeNotFalse matchers #452 by @IsabelleNP  
- [x] Improves Failures implementation #465 
- [x] Fix 479 - wrong assertion on shouldThrow #484

Remaining out of this release are features still to be improved, such as Kotlin 1.3 support, coroutines support and some others, which will be delivered when they're 100% ready and perfected

**Comment by sksamuel** [comment]
#434 #464 is improvement only and should move to 3.2.0 only IMO.
Is #465 potentially breaking, same with #477, if so they should be 3.2.0 only as well.

Rest I think we can cherry pick and release.

**Comment by checketts** [comment]
@Kerooker do you need me to do anything? Or was I just mentioned to keep me in the loop?

**Comment by Kerooker** [comment]
@checketts Not at the moment, don't worry. I was just giving you credit for your changes :+1:

**Comment by Kerooker** [comment]
@sksamuel Agreed with you on #434 and #464. However, I don't understand why #465 can be potentially breaking, as it was an improvement to a fix you made. I also don't mind postponing #477 to 3.2.0

**Comment by sksamuel** [comment]
Yes you're right.

**Comment by Kerooker** [comment]
Ok, I removed #434, #464 and #477 . I'll cherry pick other pull requests and submit a pull request

**Comment by Kerooker** [comment]
I tried to cherry pick, but it ended with many compilation errors, because some commits made some changes that were not picked up

**Comment by sksamuel** [comment]
That's where you have to edit them :)

**Comment by sksamuel** [comment]
If you can checkout the release/3.1.x branch and have a look over it see if it looks good, I will release it.

**Comment by Kerooker** [comment]
Crap. You did in 30 min what I was trying for some hours to do :P

Can https://github.com/kotlintest/kotlintest/pull/484 go along? It's a small fix and won't change any user code

**Comment by sksamuel** [comment]
Ok that's added too.

**Comment by Kerooker** [comment]
Than I think everything is fine. Let me know if you need any help.

**Comment by Kerooker** [comment]
@sksamuel I fixed the branch

**Comment by Kerooker** [comment]
I think it's released, then?

**Comment by sksamuel** [comment]
Yep.
